package dev.subfly.rickmmorty.android.common.theme.green
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4B6700)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC9F077)
val md_theme_light_onPrimaryContainer = Color(0xFF141F00)
val md_theme_light_secondary = Color(0xFF006E2C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF90F99E)
val md_theme_light_onSecondaryContainer = Color(0xFF002108)
val md_theme_light_tertiary = Color(0xFF1B6D10)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFA2F78A)
val md_theme_light_onTertiaryContainer = Color(0xFF012200)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFCF4)
val md_theme_light_onBackground = Color(0xFF1B1C17)
val md_theme_light_surface = Color(0xFFFEFCF4)
val md_theme_light_onSurface = Color(0xFF1B1C17)
val md_theme_light_surfaceVariant = Color(0xFFE2E4D4)
val md_theme_light_onSurfaceVariant = Color(0xFF45483C)
val md_theme_light_outline = Color(0xFF76786B)
val md_theme_light_inverseOnSurface = Color(0xFFF2F1E9)
val md_theme_light_inverseSurface = Color(0xFF30312C)
val md_theme_light_inversePrimary = Color(0xFFADD45E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4B6700)
val md_theme_light_outlineVariant = Color(0xFFC6C8B9)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFADD45E)
val md_theme_dark_onPrimary = Color(0xFF253600)
val md_theme_dark_primaryContainer = Color(0xFF374E00)
val md_theme_dark_onPrimaryContainer = Color(0xFFC9F077)
val md_theme_dark_secondary = Color(0xFF74DC85)
val md_theme_dark_onSecondary = Color(0xFF003913)
val md_theme_dark_secondaryContainer = Color(0xFF00531F)
val md_theme_dark_onSecondaryContainer = Color(0xFF90F99E)
val md_theme_dark_tertiary = Color(0xFF87DA71)
val md_theme_dark_onTertiary = Color(0xFF023900)
val md_theme_dark_tertiaryContainer = Color(0xFF055300)
val md_theme_dark_onTertiaryContainer = Color(0xFFA2F78A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1C17)
val md_theme_dark_onBackground = Color(0xFFE4E3DB)
val md_theme_dark_surface = Color(0xFF1B1C17)
val md_theme_dark_onSurface = Color(0xFFE4E3DB)
val md_theme_dark_surfaceVariant = Color(0xFF45483C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C8B9)
val md_theme_dark_outline = Color(0xFF909284)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1C17)
val md_theme_dark_inverseSurface = Color(0xFFE4E3DB)
val md_theme_dark_inversePrimary = Color(0xFF4B6700)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFADD45E)
val md_theme_dark_outlineVariant = Color(0xFF45483C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA7CD58)
